### ISSUE TITLE
task list not processed anymore

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-robot#136]
Seems that is can happens that a service doesn't process its task list.
We've seen this by the https://github.com/zero-os/0-templates/tree/master/templates/zeroos_bootstrap template.

After a while, the service just stop processing new tasks.

**Comment by chrisvdg** [comment]
@zaibon can you give more information how it could be possible to reproduce this?
And you just check the zrobot output if it's still processing tasks?

**Comment by zaibon** [comment]
This has been solved by hardening the bootstrap template. So closing for now. Will pop out soon enough if it still exists
