### ISSUE TITLE
Improve upgrade service flow

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-robot#151]
Currently the layout on disk for the templates is:
```
templates/{template_name}/template.py
templates/{template_name}/schema.capnp
```

This doesn't take in account the version of the template.
But for upgrade of services to be possible, we need a way for 2 version of the same templates to be present at the same time.
So when a new template version is ready, we can pull the template repository, get the new code on the robot, then upgrade the services.

We could allow something like
```
templates/{template_name}/{version}/template.py
templates/{template_name}/{version}/schema.capnp
```
With this file layout we can have 2 templates with different version present.

**Comment by zaibon** [comment]
OK, that sounds reasonable. Now we need to define how an upgrade script should look.

**Comment by zaibon** [comment]
If we go that path, that means that we can remove the upgrade service method from the API altogether cause then the version of the templates/services will be dictated by the template themself. 
So if there are some existing services and we update the associated templates, the services will upgrade automatically to the newer version.

Same apply when we start the robot with templates that are newer then the existing services. During the services loading phase a the start of the robot we need to uprade them.

**Comment by zaibon** [comment]
closed by https://github.com/zero-os/0-robot/commit/9b7f07b8cbe83e55113c8d56a02fbb2c2701bbf6

**Comment by ahmedelsayed-93** [comment]
verified @ ```development:112392f```
