### ISSUE TITLE
Improve user secret logic

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-robot#183]
currently for each service on a robot we create, a new 0-robot client is create into the config manager to keep the secret. that is a big overkill and would be better if we could keep all the secret into the same configuration

**Comment by zaibon** [comment]
Change regarding secret location has been done in https://github.com/zero-os/0-robot/commit/e13f5df1f7e873c0430bee9e239582ae82daf5cf

Still remaining, also enforce authentication regarding scheduling action when using blueprint. Currently you can still schedule action on any service when using blueprint.

**Comment by ahmedelsayed-93** [comment]
development fdfe7c81
