### ISSUE TITLE
Specify service name in error message of ServiceNotFoundError

### ISSUE THREAD

**Issue by katia-e** [zero-os/0-robot#198]
### Problem
ServiceNotFoundError doesn't expose name of the nonexistent service.

Feature requested by  @john-kheir in this [ticket ](https://github.com/openvcloud/0-templates/issues/117)

**Comment by zaibon** [comment]
This need to be handled at the application/template level. The robot can raise this error in different places and the query to get a service can also be different, so there is no common format we can use to describe which service was not found.

Application code need to catch this exception and wrap it to have a clear error message for the user
