### ISSUE TITLE
0-robot task.result returns None when False is returned from action

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-robot#201]
When an action is scheduled and returns `False`, `None` is returned in `task.result` instead.

### start robot using template that has actions returning boolean values
```sh
zrobot server start -D <data_repo> -C <config_repo> -T git@github.com:chrisvdg/zrobot-helloworld.git
```
### Call those actions (using jumpscale)
```py
# create service
s = robot.services.find_or_create("github.com/chrisvdg/zrobot-helloworld/helloworld/0.0.1", "s1", {})

task = s.schedule_action('return_false')
task.wait()
print(task.result)
# Out: None

# returning True works fine
task = s.schedule_action('return_true')
task.wait()
print(task.result)
# Out: True
```

**Comment by katia-e** [comment]
False becomes None here: `/github/zero-os/0-robot/zerorobot/server/handlers/views.py`
![image](https://user-images.githubusercontent.com/32639869/40004902-fe716476-5796-11e8-9331-97c1726f018e.png)
