### ISSUE TITLE
Getting "no signing key available" when running blueprint using different user other than root

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-robot#208]
## Scenario
1 - I'm using a key inside /root/.ssh as defined by https://github.com/zero-os/0-robot/blob/development/zerorobot/robot/config_repo.py#L76

2- Run any blueprint to do anything which is using "travis" user

## Error

```
urllib3.connectionpool: DEBUG: http://localhost:6600 "POST /blueprints HTTP/1.1" 500 78
openvcloud_testsuite: INFO: message: error creating user secret: no signing key available
```

## Note 
Most probably while running the blueprint.. it is looking for keys inside the home directory (/home/travis) which is not /root in this case

please check:  https://github.com/zero-os/0-robot/blob/config-key/zerorobot/server/auth/user_jwt.py#L56

**Comment by zaibon** [comment]
fixed by #207
