### ISSUE TITLE
add_repo() doesn't switch to the given branch

### ISSUE THREAD

**Issue by katia-e** [zero-os/0-robot#213]
When adding repo to the robot with method `add_repo(url, revision)`, robot doesn't not checkout  given branch, and checkouts master instead.

**Additional note**
Methods `checkout_repo(url, revision)` and `add_repo(url, branch)` have different name for the same positional argument.

**Comment by zaibon** [comment]
Can you provide full scenario cause I just tried:
```python
local.templates.add_repo('https://github.com/zaibon/0-boot-templates.git','zaibon-patch-1')
Out[2]: 
[<JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f15776570f0>,
 <JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f1577657128>,
 <JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f1577657160>,
 <JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f1577657198>,
 <JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f15776571d0>,
 <JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f1577657208>,
 <JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f1577657240>,
 <JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f1577657278>,
 <JumpScale9Zrobot.clients.zerorobot.client.Template.Template at 0x7f15776572b0>]
```

```
# pwd
/opt/code/github/zaibon/0-boot-templates
root@js9:/opt/code/github/zaibon/0-boot-templates# git status
On branch zaibon-patch-1
Your branch is up-to-date with 'origin/zaibon-patch-1'.
nothing to commit, working directory clean
```

and the repo is properly cloned and the branch is checkedout

**Comment by katia-e** [comment]
1. Run zos machine and connect to the node robot. 
`robot = j.clients.zrobot.robots["zos_local_robot"]`
2. Add repo 
`robot.templates.add_repo('https://github.com/threefoldtoken/0-templates.git', 'block_creator')`
Then I list actions on this template
![image](https://user-images.githubusercontent.com/32639869/40534828-95a288a2-6007-11e8-8a7c-5fcf65691d52.png)
and the methods I added on branch `block_creator`are not there,
3. Checkout branch
![image](https://user-images.githubusercontent.com/32639869/40534926-db3cc49a-6007-11e8-8826-a7d02b0e51f0.png)
In the result `peer_discovery()` method is present in the list of actions, but it appear only after `repo_checkout`

**Comment by katia-e** [comment]
Problem appeared as my mistake.
