### ISSUE TITLE
Can't find any services after upgrading from 0.5.x to 0.7 using the migration script

### ISSUE THREAD

**Issue by LeeSmet** [zero-os/0-robot#221]
After rebooting last night (updating the robot from 0.5.x to presumably 0.7 on the node), and using the migration script provided, my client (0.7.1) is unable to find any services.

**Comment by zaibon** [comment]
Seems problem came from how jumpscale detect the `HOME` directory.
https://github.com/zero-os/0-robot/commit/6cf756843522a021e72f73314750756f06ea6397 should fix it

**Comment by zaibon** [comment]
another fix regarding this issue: https://github.com/zero-os/0-robot/commit/985c1cdfbb1d0160d3899d2508c42690f74b0c26
