### ISSUE TITLE
deleting service doesn't stop its recurring actions

### ISSUE THREAD

**Issue by xmonader** [zero-os/0-robot#234]
Deleting service doesn't stop its recurring action

0-robot version: `commit 7e7d5658b5abcb6e4574bfe24b5f08f9031225f7 (HEAD -> master, tag: v0.7.2, origin/master, origin/HEAD)`

# How to reproduce

```python
from js9 import j

from zerorobot.template.base import TemplateBase
from zerorobot.template.state import StateCheckError

class Helloworld(TemplateBase):

    version = '0.0.2'
    template_name = "helloworld"

    def __init__(self, name=None, guid=None, data=None):
        super().__init__(name=name, guid=guid, data=data)

        if not self.data['msg']:
            self.data['msg'] = "hello world"

        self.recurring_action("greeter", 5)

    def validate(self):
        if not self.data['msg'].islower():
            raise ValueError("MSG {} should be lower.".format(self.data['msg']))

    def greeter(self):
        self.logger.info("RECUR: {}".format(self.data['msg']))

    def install(self):
        self.logger.info("Installing hello world service ({})".format(self.data['msg']))
        

    def uninstall(self):
        self.logger.info("uninstalling hello world service ({})".format(self.data['msg']))


```

```
s1 = robot.services.create("github.com/xmonader/0-playground/helloworld/0.0.2", "first_service")
s1,delete()
```

# Expected
Stop recurring action 

# Actual
it keeps printing to stdout

**Comment by zaibon** [comment]
@xmonader would be nice to have the logs of the robot for this test.
also do you confirm that the recurring action continue to live forever until the robot is stopped completely ? or does the action just runs one more time after the service is deleted ?

**Comment by xmonader** [comment]
@zaibon I can't reproduce it again. The recurring action continued to forever and The gl_mgr had an orphaned recurring before, but now I can't reproduce it.

**Comment by zaibon** [comment]
ok I'll set this to minor then. if you ever get a way to reproduce let me know
