### ISSUE TITLE
After restarting node node robot thinks HOME=/ and not HOME=/root

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-robot#242]
After deleting the state of a node robot, and restarting the node robot like this:
```python
...
zrobot1_container = zos_sal1.containers.get(name='zrobot')
zrobot1_container.client.bash(script='rm -rf /opt/var/data/zrobot/zrobot_data/*').get()
zrobot1_container.stop()
zrobot1_container.start()
```

I see this the node output:
```
Could not execute: sshkey-gen -t rsa -b 4096 ‘’-f /.ssh/a57fght -> no such file or directory
```

**Comment by chrisvdg** [comment]
Had the same issue the 0-robot started with 0-os on a host in the Mazraa farm that rebooted
![image](https://user-images.githubusercontent.com/23582741/41720246-b48c4b66-7562-11e8-9141-35bd1c01b062.png)

**Comment by zaibon** [comment]
can you give more info:
- what was the version running before the reboot ? ipxe url, ... ?

**Comment by chrisvdg** [comment]
ipxe boot using usb with https://bootstrap.gig.tech/usb/master/9f77fc393ef00142/development
Booted first around 05/06/2018

**Comment by FastGeert** [comment]
With this script you can temp fix it:
```
    robocon = node.containers.get("zrobot")
    buf = BytesIO()
    robocon.client.filesystem.download("/root/js9host/cfg/jumpscale9.toml", buf)
    data = toml.loads(buf.getvalue().decode("utf8"))
    if data["dirs"]["HOMEDIR"] != "/root":
        print("***** FIXING JS HOMEDIR *****" % node_id)
        data["dirs"]["HOMEDIR"] = "/root"
        buf = BytesIO(toml.dumps(data).encode("utf8"))
        buf.seek(0)
        robocon.client.filesystem.upload("/root/js9host/cfg/jumpscale9.toml", buf)
        robocon.stop()
```

**Comment by zaibon** [comment]
fixed in https://github.com/zero-os/0-robot/commit/985c1cdfbb1d0160d3899d2508c42690f74b0c26
