### ISSUE TITLE
deal with sensitive data coming from blueprint

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-robot#44]
We need something that allow us to deal with sensitive data send to the 0-robot.
Since all the schema data of the services is kept on the filesystem in text files, we need to make sure to not keep password, secret, api token,... present in these files.

The idea is the following:
- 0-robot API needs to be server over TLS
- Services that receives sensitive information needs to use [jumpscale config manager](https://github.com/Jumpscale/core9/blob/development/docs/config/configmanager.md) to store this data securely and make sure that we don't store them in the data schema of the service.

**Comment by yveskerwyn** [comment]
Next to leveraging the config manager we need:
- a RESTful API to configure the involved js config instances, in AYS 9.3.0 we have this: https://github.com/openvcloud/ays_templates/tree/master/docs/OVC_Client
- 0-templates leveraging this RESTful API

In AYS 9.3.0:
- the OVC config instances are created per AYS repository, $REPO-NAME_INSTANCE-NAME
- only one ItsYou.online config instance is supported, named `main`

Not sure how this will/should map in 0-robot-space...
