### ISSUE TITLE
Find an easy way to choose on which robot to deploy a service

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-robot#86]
Currently if you have multiple robot connection configured and you try to install a robot using
`self.api.services.create` the code will look at each robot, which one has the requested templates loaded and if multiple robot have the template, one will be choosen randomly.

While this works great for simple use case where you don't really care where the services are running.
This don't allow you to choose which robot is supposed to deal with which services.

In the furture we want to deploy one 0-robot per 0-os node. This to spread the load, and make a robot responsible to manage a full node.
With that in mind, we need a way to be able to decide on which node/robot we want the services to be deployed.
Currently this is a bit tricky cause the `zero-os/node` template doesn't have any notion of robot or anyhting so we can't map a node to a robot.

**Comment by muhamadazmy** [comment]
This sounds like we need to think about capacity planning.

If we have a robot/node (is the robot responsible for a node gonna live on the node itself?) the robot must know how much resources is remaining, hence the client can query this info, and whoever has enough resource to run a service should take it.

I think we should keep in mind the CP negotiation when thinking about #87
