### ISSUE TITLE
auto download needed template repos

### ISSUE THREAD

**Issue by muhamadazmy** [zero-os/0-robot#88]
Since a template is specified by it's full ID (including host and org) robot should be able to find the needed template repo, and even clone it locally if needed, without the need to specify the template repos on command line

may be we define or specify a TEMPLATEPATH (like GOPATH) where the robot can search for template repos and download repos to if needed

**Comment by zaibon** [comment]
I like the idea but this is currently not possible with the robot as it is now, cause the code now uses the loaded template of a robot to decide where a service can be install.
Once we have solve #86, I think this feature could be implemented.

**Comment by zaibon** [comment]
I like the idea but this is currently not possible with the robot as it is now, cause the code now uses the loaded template of a robot to decide where a service can be install.
Once we have solve #86, I think this feature could be implemented.

although this bring another question, do we want anyone that can talk to the robot to force it to download template, which means code, that could be a pretty dangerous things to do
